### ISSUE TITLE
Unable to get the project working

### ISSUE THREAD

**Issue by Hervian** [SwissArmyRonin/swagger-packaging-maven-plugin#1]
Hi

This plugin looks just like something I need. I have 1 comment and 1 question though:

1. 
The documentation should be updated, since version 1.1 of the plugin does not seem to work, but gives an error relating to the packaging type.  

2.
I am unable to install my example-service into local .m2 repository. Is running `mvn clean install` not enough? My goal is to be able to run `mvn dependency:copy -Dartifact=my.company:example-service:1.0:yaml -DoutputDirectory=.` from a command prompt and have the swagger yaml file be downloaded from my local .m2 repository (or a remote one in case not found locally and a remote is configured). Or have I misunderstood the basic usage?

**Comment by mhvelplund** [comment]
Anything that runs the `package` step should trigger the mojo. I've confirmed that it doesn't work (anymore), but I'm not sure what happened.

**Comment by mhvelplund** [comment]
Ok; if you only need YAML support, use version 1.1 of the plugin. The following works if you have a YAML file at `src/main/resources/example.yaml`

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dk.swissarmyronin.services</groupId>
  <artifactId>example-service</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>swagger</packaging> <!-- Note that the packaging name is different in 1.1 -->
  <build>
    <plugins>
      <plugin>
        <groupId>dk.swissarmyronin</groupId>
        <artifactId>swagger-packaging-maven-plugin</artifactId>
        <version>1.1</version>
        <extensions>true</extensions>
        <configuration>
          <sourceDir>${basedir}/src/main/resources</sourceDir>
          <swaggerFile>example.yaml</swaggerFile>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

Version 1.2 added JSON support, and something seems to be broken with that version.
